config/routes.rb
TwantApp::Application.routes.draw do
  get "users/new"

  root to: 'static_pages#home'
  match '/halp', to: 'static_pages#halp'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/getsome', to: 'users#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation
  has_secure_password
  
  before_save { |user| user.email = email.downcase }
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end

  def HALP
  end
  
  def about
  end
  
  def getsome
  end
  
  def contact
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  # Returns the full title or crops if no specific title provided
  def full_title(page_title)
    base_title = "TwantApp"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		<a href="http://4.bp.blogspot.com/-oGuGlDLNMEU/UA4_NhkF9VI/AAAAAAAABy0/2z3UH7oQ5ww/s1600/IMG_20120722_230045-765789.jpg">These pants?</a> ARE MINE!
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://images.cheezburger.com/completestore/2010/2/19/129111063957048309.jpg">News</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top" >
	<div class="navbar-inner">
		<div class="container">
			<%= link_to "twant app", root_path, id: 'logo' %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "About", about_path %></li>
					<li><%= link_to "Contact", contact_path %></li>
					<li><%= link_to "HALP!", halp_path %></li>
					<li><%= link_to "Get some...", getsome_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= full_title( yield( :title ) )%></title>
  		<%= stylesheet_link_tag    "application", :media => "all" %>
  		<%= javascript_include_tag "application" %>
  		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class= "container">
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
	<p>Really, <a href="http://i57.photobucket.com/albums/g223/mudshark58/cartoons/another-great-moment-in-evo.gif">this is all you need to know</a></p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact...</h1>
	<p>Let's make...<a href="http://images.wikia.com/muppet/images/c/c8/321contact.jpg">CONTACT!</a></p>
	<p>3</p>
	<p>2</p>
	<p>1</p>
	<p>...</p>
	<p><a href= "http://www.youtube.com/watch?v=s2-LEBc2sO8">Contact.</a></p>

app/views/static_pages/halp.html.erb
<% provide(:title, 'HALP') %>
<h1>HALP!</h1>
	<p>You have been messing with <a href="http://summitlake.com/graphics/wp-graphics/uploads/Gary-Larson-do-not-touch.gif">the wrong things</a> perhaps?</p>

app/views/static_pages/help.html.erb
<h1>HALP!</h1>
	<p>You have been messing with <a href="http://summitlake.com/graphics/wp-graphics/uploads/Gary-Larson-do-not-touch.gif">the wrong things</a> perhaps?</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>TwantApp</h1>
		
		<h2>Home is where the <a href="http://i.huffpost.com/gen/274325/AM-I-WEARING-PANTS.jpg">PANTS</a> are.
		</h2>
		<%= link_to "Get some!", getsome_path, class: "btn btn-large btn-primary" %>
</div>
<div class="center">
<%= link_to image_tag("bunnyRabbits.jpg", alt: "BUNNIES!"),'http://1.bp.blogspot.com/-3XBUPZtl2hk/TkzFiB6HxgI/AAAAAAAAA_Q/z4rxNi333T0/s1600/cute+bunny+011.jpg' %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Get Some') %>
<h1>Get Some</h1>
<p> GIVE US ALL OF THE PANTS </p>